spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "user"
    password:


  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console.enabled: true
    console.path: /h2-console

loan:
  paylater:
    frequency: 4
    maxAmount: 600
    
server:
  port: 8180

customer-accounts:
  api:
    url: http://localhost:8280/accounts/v1


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        recordExceptions:
          - java.net.ConnectException
        ignoreExceptions:
          - com.dagim.loan.exception.BusinessException        
    instances:
      loanBreaker:
        baseConfig: default


