spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "user"
    password:


  jpa:
    generate-ddl: true
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console.enabled: true
    console.path: /h2-console


accounts:
  loan:
    maxAmount: -600
  checkings:
    minAmount: 50
  savings:
    minAmount: 250
    
server:
  port: 8280
  error:
    include-exception: false
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ON_PARAM

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        recordExceptions:
          - feign.RetryableException
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpServerErrorException.InternalServerError
        ignoreExceptions:
          - com.customer.accounts.exception.BusinessException
    instances:
      accountsBreaker:
        baseConfig: default

